from pyspark.sql.types import StructType, ArrayType, StringType, MapType

from open_commerce_data_pipelines.core.schemas.conexxus import FINALIZE_REWARDS_REQUEST_SCHEMA
from open_commerce_data_pipelines.core.schemas.objects.activate_core import CAMPAIGNS_SCHEMA, \
    MEMBERSHIP_POINT_TRANSACTIONS_SCHEMA, OFFERS_SCHEMA, TRANSACTION_DATA_SCHEMA, TRANSACTIONS_SCHEMA, \
    OFFER_PURCHASES_SCHEMA, \
    LOYALTY_EVENTS_SCHEMA, CONSTRAINTS_SCHEMA, FUEL_AND_CONVENIENCE_PROFILES_SCHEMA, ADDRESSES_SCHEMA
from open_commerce_data_pipelines.core.schemas.objects.activate_rule import RULE_FULFILLMENTS_SCHEMA, VOUCHER_SCHEMA, \
    RULES_SCHEMA, LIMITERS_SCHEMA, ACTIONS_SCHEMA
from open_commerce_data_pipelines.core.schemas.objects.external_loyalty import OFFER_ACTIVITY_LOG_SCHEMA
from open_commerce_data_pipelines.core.schemas.objects.marketing_automation import SMS_OPT_OUT_SCHEMA, \
    COMMUNICATION_PREFERENCES_SCHEMA
from open_commerce_data_pipelines.core.schemas.objects.member_dossier import MEMBER_DOSSIER_SCHEMA
from open_commerce_data_pipelines.core.schemas.objects.open_commerce import ADDRESS_SCHEMA, CUSTOMER_SCHEMA, \
    LOCATION_SCHEMA, SITE_STATUS_SCHEMA, SITE_SYSTEM_SCHEMA, BRAND_SCHEMA, TRANSACTION_SCHEMA, SURVEY_SCHEMA, \
    SURVEY_INSTANCE_SCHEMA, SURVEY_QUESTION_SCHEMA, SURVEY_FIELD_SCHEMA, SURVEY_QUESTION_ANSWER_SCHEMA, \
    WALLET_STEERING_SCHEMA, WALLET_STEERING_CONFIGURATION_SCHEMA

ACTIONS_BRONZE_STAGE_1_SCHEMA = (StructType([*ACTIONS_SCHEMA.fields])
                                 .add("timestamp", "timestamp"))

ADDRESS_BRONZE_STAGE_1_SCHEMA = (StructType([*ADDRESS_SCHEMA.fields])
                                 .add("timestamp", "timestamp"))

ADDRESSES_BRONZE_STAGE_1_SCHEMA = (StructType([*ADDRESSES_SCHEMA.fields])
                                   .add("timestamp", "timestamp"))

BRAND_BRONZE_STAGE_1_SCHEMA = (StructType()
                               .add("createdAt", "timestamp")
                               .add("updatedAt", "timestamp")
                               .add("uuid", "string")
                               .add("id", "integer")
                               .add("name", "string")
                               .add("supportedPaymentTypes", ArrayType(StringType()))
                               .add("supportedApplePayPaymentTypes", ArrayType(StringType()))
                               .add("supportedGoogleWalletPaymentTypes", ArrayType(StringType()))
                               .add("tenantId", "integer")
                               .add("createdById", "integer")
                               .add("updatedById", "integer")
                               .add("timestamp", "timestamp"))

CHANGES_BRONZE_STAGE_1_SCHEMA = (StructType()
                                 .add("partitionKey", "string")
                                 .add("data", "binary")
                                 .add("stream", "string")
                                 .add("shardId", "string")
                                 .add("sequenceNumber", "string")
                                 .add("approximateArrivalTimestamp", "timestamp")
                                 .add("day_id", "date")
                                 .add("timestamp", "timestamp"))

CHANGES_BRONZE_STAGE_2_DATA_METADATA_SCHEMA = (StructType()
                                               .add("operation", "string", False)
                                               .add("partition-key-type", "string", False)
                                               .add("record-type", "string", False)
                                               .add("schema-name", "string", False)
                                               .add("table-name", "string", False)
                                               .add("timestamp", "timestamp", False)
                                               .add("transaction-id", "long"))

CHANGES_BRONZE_STAGE_2_DATA_SCHEMA = (StructType()
                                      .add("data", "string")
                                      .add("metadata", CHANGES_BRONZE_STAGE_2_DATA_METADATA_SCHEMA))

CHANGES_BRONZE_STAGE_2_SCHEMA = (StructType()
                                 .add("partitionKey", "string")
                                 .add("data", CHANGES_BRONZE_STAGE_2_DATA_SCHEMA)
                                 .add("stream", "string")
                                 .add("shardId", "string")
                                 .add("sequenceNumber", "string")
                                 .add("approximateArrivalTimestamp", "timestamp")
                                 .add("day_id", "date")
                                 .add("timestamp", "timestamp"))

CHANGES_BRONZE_STAGE_3_SCHEMA = (StructType()
                                 .add("change_type", "string")
                                 .add("day_id", "date")
                                 .add("data", "string")
                                 .add("table_name", "string")
                                 .add("approx_arrival_timestamp", "timestamp")
                                 .add("timestamp", "timestamp"))

CAMPAIGNS_BRONZE_STAGE_1_SCHEMA = (StructType([*CAMPAIGNS_SCHEMA.fields])
                                   .add("timestamp", "timestamp"))

CHAINS_BRONZE_STAGE_1_SCHEMA = (StructType()
                                .add("id", "string")
                                .add("name", "string")
                                .add("deleted_at", "timestamp")
                                .add("created_at", "timestamp")
                                .add("updated_at", "timestamp")
                                .add("organization_id", "string")
                                .add("membership_activity_evidence", ArrayType(StringType()))
                                .add("brand_uuid", "string")
                                .add("default_points_expiration_days", "integer")
                                .add("paused_points_expiration_days", "integer")
                                .add("timestamp", "timestamp"))

COMMUNICATION_PREFERENCES_BRONZE_STAGE_1_SCHEMA = (StructType([*COMMUNICATION_PREFERENCES_SCHEMA.fields])
                                                   .add("timestamp", "timestamp"))

CONSTRAINTS_BRONZE_STAGE_1_SCHEMA = (StructType([*CONSTRAINTS_SCHEMA.fields])
                                     .add("timestamp", "timestamp"))

CUSTOMER_BRONZE_STAGE_1_SCHEMA = (StructType([*CUSTOMER_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

FUEL_AND_CONVENIENCE_PROFILES_BRONZE_STAGE_1_SCHEMA = (StructType([*FUEL_AND_CONVENIENCE_PROFILES_SCHEMA])
                                                       .add("timestamp", "timestamp"))

KINESIS_MESSAGE_STAGE_1_SCHEMA = (StructType()
                          .add("partitionKey", "string")
                          .add("data", "binary")
                          .add("shardId", "string")
                          .add("sequenceNumber", "string")
                          .add("received_at", "timestamp")
                          .add("written_at", "timestamp")
                          .add("source_name", "string")
                          .add("last_processed_at", "timestamp")
                          .add("last_processing_status", "string")
                          .add("last_processing_message", "string")
                          .add("day_id", "date"))

LIMITERS_BRONZE_STAGE_1_SCHEMA = (StructType([*LIMITERS_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

LOCATION_BRONZE_STAGE_1_SCHEMA = (StructType()
                                  .add("createdAt", "timestamp")
                                  .add("updatedAt", "timestamp")
                                  .add("id", "integer")
                                  .add("uuid", "string")
                                  .add("brandSpecificLocationId", "string")
                                  .add("addressId", "integer")
                                  .add("createdById", "integer")
                                  .add("updatedById", "integer")
                                  .add("specialHours", "string")
                                  .add("brandId", "integer")
                                  .add("currencyCode", "string")
                                  .add("currencySymbol", "string")
                                  .add("timezone", "string")
                                  .add("deletedAt", "timestamp")
                                  .add("deletedById", "integer")
                                  .add("attributes", "string")
                                  .add("hoursOfOperation",
                                       StructType()
                                       .add("hours",
                                            ArrayType(StructType()
                                                      .add("openTime", "string")
                                                      .add("closeTime", "string")
                                                      .add("dayOfWeek", "string"))))
                                  .add("paymentProviderMerchantId", "string")
                                  .add("altriaRcn", "string")
                                  .add("timestamp", "timestamp"))

LOYALTY_EVENTS_BRONZE_STAGE_1_SCHEMA = (StructType([*LOYALTY_EVENTS_SCHEMA.fields])
                                        .add("day_id", "date")
                                        .add("timestamp", "timestamp"))

MEMBER_DOSSIER_BRONZE_STAGE_1_SCHEMA = (StructType([*MEMBER_DOSSIER_SCHEMA.fields])
                                        .add("timestamp", "timestamp"))

MEMBERSHIP_POINT_TRANSACTIONS_BRONZE_STAGE_1_SCHEMA = (StructType([*MEMBERSHIP_POINT_TRANSACTIONS_SCHEMA.fields])
                                                       .add("day_id", "date")
                                                       .add("timestamp", "timestamp"))

MEMBERSHIPS_BRONZE_STAGE_1_SCHEMA = (StructType()
                                     .add("id", "string")
                                     .add("chain_id", "string")
                                     .add("email", "string")
                                     .add("phone", "string")
                                     .add("deleted_at", "timestamp")
                                     .add("created_at", "timestamp")
                                     .add("updated_at", "timestamp")
                                     .add("state", "string")
                                     .add("points", "integer")
                                     .add("name", "string")
                                     .add("encrypted_password", "string")
                                     .add("reset_password_token", "string")
                                     .add("reset_password_sent_at", "timestamp")
                                     .add("custom_data", "string")
                                     .add("birthdate", "date")
                                     .add("first_name", "string")
                                     .add("last_name", "string")
                                     .add("failed_attempts", "integer")
                                     .add("unlock_token", "string")
                                     .add("locked_at", "timestamp")
                                     .add("activity_at", "timestamp")
                                     .add("customer_uuid", "string")
                                     .add("program_terms_acceptance_at", "timestamp")
                                     .add("home_stores", ArrayType(StringType()))
                                     .add("timestamp", "timestamp"))

MEMBERSHIPS_SEGMENTS_BRONZE_STAGE_1_SCHEMA = (StructType()
                                              .add("id", "string")
                                              .add("membership_id", "string")
                                              .add("segment_id", "string")
                                              .add("deleted_at", "timestamp")
                                              .add("created_at", "timestamp")
                                              .add("updated_at", "timestamp")
                                              .add("csv_upload", "boolean")
                                              .add("timestamp", "timestamp"))

META_OFFERS_BRONZE_STAGE_1_SCHEMA = (StructType()
                                     .add("id", "string")
                                     .add("fuel_grade_id", "string")
                                     .add("offer_value", "double")
                                     .add("limit", "integer")
                                     .add("offers_ids", ArrayType(StringType()))
                                     .add("parent_id", "string")
                                     .add("created_at", "timestamp")
                                     .add("updated_at", "timestamp")
                                     .add("loyalty_sequence_id", "string")
                                     .add("day_id", "date")
                                     .add("timestamp", "timestamp"))

OFFER_ACTIVITY_LOG_BRONZE_STAGE_1_SCHEMA = (StructType([*OFFER_ACTIVITY_LOG_SCHEMA.fields])
                                            .add("day_id", "date")
                                            .add("timestamp", "timestamp"))

OFFER_PURCHASES_BRONZE_STAGE_1_SCHEMA = (StructType([*OFFER_PURCHASES_SCHEMA.fields])
                                         .add("day_id", "date")
                                         .add("timestamp", "timestamp"))

OFFERS_BRONZE_STAGE_1_SCHEMA = (StructType([*OFFERS_SCHEMA.fields])
                                .add("timestamp", "timestamp"))

PRODUCT_GROUPS_BRONZE_STAGE_1_SCHEMA = (StructType()
                                        .add("id", "string")
                                        .add("chain_id", "string")
                                        .add("name", "string")
                                        .add("description", "string")
                                        .add("key", "string")
                                        .add("values", ArrayType(StringType()))
                                        .add("created_at", "timestamp")
                                        .add("updated_at", "timestamp")
                                        .add("deleted_at", "timestamp")
                                        .add("timestamp", "timestamp"))

PRODUCTS_BRONZE_STAGE_1_SCHEMA = (StructType()
                                  .add("id", "string")
                                  .add("manufacturer", "string")
                                  .add("manufacturer_parent_company", "string")
                                  .add("brand", "string")
                                  .add("product_line", "string")
                                  .add("upc", "string")
                                  .add("selling_unit", "double")
                                  .add("selling_unit_of_measure", "string")
                                  .add("display_name_template", "string")
                                  .add("sample_image_url", "string")
                                  .add("attributes", MapType(StringType(), StringType()))
                                  .add("categories", ArrayType(StringType()))
                                  .add("created_at", "timestamp")
                                  .add("updated_at", "timestamp")
                                  .add("timestamp", "timestamp"))

RULE_FULFILLMENTS_BRONZE_STAGE_1_SCHEMA = (StructType([*RULE_FULFILLMENTS_SCHEMA.fields])
                                           .add("day_id", "date")
                                           .add("timestamp", "timestamp"))

RULES_BRONZE_STAGE_1_SCHEMA = (StructType([*RULES_SCHEMA.fields])
                               .add("timestamp", "timestamp"))

SITE_STATUS_BRONZE_STAGE_1_SCHEMA = (StructType([*SITE_STATUS_SCHEMA.fields])
                                     .add("timestamp", "timestamp"))

SITE_SYSTEM_BRONZE_STAGE_1_SCHEMA = (StructType([*SITE_SYSTEM_SCHEMA.fields])
                                     .add("timestamp", "timestamp"))

SMS_OPT_OUT_BRONZE_STAGE_1_SCHEMA = (StructType([*SMS_OPT_OUT_SCHEMA.fields])
                                     .add("day_id", "date")
                                     .add("timestamp", "timestamp"))

TRANSACTION_BRONZE_STAGE_1_SCHEMA = (StructType()
                                     .add("createdAt", "timestamp")
                                     .add("updatedAt", "timestamp")
                                     .add("id", "integer")
                                     .add("uuid", "string")
                                     .add("customerUuid", "string")
                                     .add("umti", "string")
                                     .add("stac", "string")
                                     .add("paymentProviderTransactionId", "string")
                                     .add("startedAt", "timestamp")
                                     .add("completedAt", "timestamp")
                                     .add("status", "string")
                                     .add("brandSpecificLocationId", "string")
                                     .add("fuelingPosition", "string")
                                     .add("authCode", "string")
                                     .add("hardwareVendor", "string")
                                     .add("transactionType", "string")
                                     .add("paymentLevel", "string")
                                     .add("loyaltyLevel", "string")
                                     .add("fuelPumpStatus", "string")
                                     .add("initiationResource", "string")
                                     .add("receiptLines", ArrayType(StringType()))
                                     .add("rawReceipt", "string")
                                     .add("fuelReceipt", "string")
                                     .add("amountDisplayprice", "string")
                                     .add("amountPrice", "double")
                                     .add("taxDisplayprice", "string")
                                     .add("taxPrice", "double")
                                     .add("refundedAmountDisplayprice", "string")
                                     .add("refundedAmountPrice", "double")
                                     .add("currencyCode", "string")
                                     .add("currencySymbol", "string")
                                     .add("additionalReceiptData", "string")
                                     .add("preAuthAmountDisplayprice", "string")
                                     .add("preAuthAmountPrice", "double")
                                     .add("locationUuid", "string")
                                     .add("primaryStatus", "string")
                                     .add("secondaryStatus", "string")
                                     .add("paymentInstrumentUuid", "string")
                                     .add("stateChanges",
                                          ArrayType(StructType()
                                                    .add("updatedAt", "timestamp")
                                                    .add("primaryStatus", "string")
                                                    .add("secondaryStatus", "string")))
                                     .add("customerPreferences",
                                          StructType()
                                          .add("printReceipt", "boolean")
                                          .add("promptForCarWash", "boolean"))
                                     .add("carWashDetails", "string")
                                     .add("isPaymentProcessedExternally", "boolean")
                                     .add("loyaltyIdentifier", "string")
                                     .add("kountSessionId", "string")
                                     .add("kountResponse", "string")
                                     .add("posTransactionNumber", "string")
                                     .add("sourceId", "integer")
                                     .add("cardType", "string")
                                     .add("paymentMethod", "string")
                                     .add("day_id", "date")
                                     .add("timestamp", "timestamp"))

TRANSACTION_DATA_BRONZE_STAGE_1_SCHEMA = (StructType([*TRANSACTION_DATA_SCHEMA.fields])
                                          .add("day_id", "date")
                                          .add("timestamp", "timestamp"))

TRANSACTION_DATA_BRONZE_STAGE_2_SCHEMA = (StructType()
                                          .add("id", "string")
                                          .add("day_id", "date")
                                          .add("transaction_id", "string")
                                          .add("processing_status", "string")
                                          .add("finalize_rewards_data", FINALIZE_REWARDS_REQUEST_SCHEMA)
                                          .add("created_at", "timestamp")
                                          .add("updated_at", "timestamp")
                                          .add("timestamp", "timestamp"))

TRANSACTION_LINE_ITEMS_BRONZE_STAGE_1_SCHEMA = (StructType()
                                                .add("id", "string")
                                                .add("transaction_id", "string")
                                                .add("line_item_number", "integer")
                                                .add("sku", "string")
                                                .add("promo_code", "string")
                                                .add("quantity", "double")
                                                .add("money_amount", "integer")
                                                .add("upc", "string")
                                                .add("group", "string")
                                                .add("line_item_tags", "string")
                                                .add("created_at", "timestamp")
                                                .add("product_groups", ArrayType(StringType()))
                                                .add("membership_id", "string")
                                                .add("transaction_time_at", "timestamp")
                                                .add("fuel_grade_id", "string")
                                                .add("promotion_data", "string")
                                                .add("day_id", "date")
                                                .add("timestamp", "timestamp"))

TRANSACTIONS_BRONZE_STAGE_1_SCHEMA = (StructType([*TRANSACTIONS_SCHEMA.fields])
                                      .add("day_id", "date")
                                      .add("timestamp", "timestamp"))

VOUCHERS_BRONZE_STAGE_1_SCHEMA = (StructType([*VOUCHER_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

SURVEY_BRONZE_STAGE_1_SCHEMA = (StructType([*SURVEY_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

SURVEY_INSTANCE_BRONZE_STAGE_1_SCHEMA = (StructType([*SURVEY_INSTANCE_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

SURVEY_QUESTION_BRONZE_STAGE_1_SCHEMA = (StructType([*SURVEY_QUESTION_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

SURVEY_QUESTION_ANSWER_BRONZE_STAGE_1_SCHEMA = (StructType([*SURVEY_QUESTION_ANSWER_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

SURVEY_FIELD_BRONZE_STAGE_1_SCHEMA = (StructType([*SURVEY_FIELD_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

WALLET_STEERING_BRONZE_STAGE_1_SCHEMA = (StructType([*WALLET_STEERING_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))

WALLET_STEERING_CONFIGURATION_BRONZE_STAGE_1_SCHEMA = (StructType([*WALLET_STEERING_CONFIGURATION_SCHEMA.fields])
                                  .add("timestamp", "timestamp"))
