from pyspark.sql.types import ArrayType, StructType

OFFER_AWARDS_GOLD_VOUCHER_STATE_HISTORY_SCHEMA = (StructType()
                                                  .add("state", "string")
                                                  .add("updated_at", "timestamp"))

OFFER_AWARDS_GOLD_STAGE_1_SCHEMA = (StructType()
                                    .add("id", "string")
                                    .add("day_id", "date")
                                    .add("loyalty_member_id", "string")
                                    .add("member_id", "string")
                                    .add("event_id", "string")
                                    .add("transaction_id", "string")
                                    .add("transaction_line_item_number", "integer")
                                    .add("meta_offer_id", "string")
                                    .add("offer_id", "string")
                                    .add("rule_id", "string")
                                    .add("award_type", "string")
                                    .add("points_quantity", "integer")
                                    .add("created_at", "timestamp")
                                    .add("updated_at", "timestamp")
                                    .add("expires_at", "timestamp")
                                    .add("user_notes", "string")
                                    .add("discount_amount", "double")
                                    .add("discount_is_site_level", "boolean")
                                    .add("voucher_offer_id", "string")
                                    .add("voucher_rule_id", "string")
                                    .add("voucher_state", "string")
                                    .add("voucher_state_history",
                                         ArrayType(OFFER_AWARDS_GOLD_VOUCHER_STATE_HISTORY_SCHEMA))
                                    .add("timestamp", "timestamp"))
