from pyspark.sql.types import StructType

OFFER_FULFILLMENTS_GOLD_STAGE_1_SCHEMA = (StructType()
                                          .add("id", "string")
                                          .add("rule_fulfillment_id", "string")
                                          .add("fulfillment_item_number", "integer")
                                          .add("day_id", "date")
                                          .add("member_id", "string")
                                          .add("loyalty_member_id", "string")
                                          .add("event_id", "string")
                                          .add("transaction_id", "string")
                                          .add("offer_purchase_id", "string")
                                          .add("vouchered_offer_id", "string")
                                          .add("rule_id", "string")
                                          .add("offer_id", "string")
                                          .add("created_at", "timestamp")
                                          .add("updated_at", "timestamp")
                                          .add("fulfillment_type", "string")
                                          .add("timestamp", "timestamp"))
