from pyspark.sql.types import StructType

TRANSACTION_ITEMS_GOLD_STAGE_1_SCHEMA = (StructType()
                                         .add("id", "string")
                                         .add("day_id", "date")
                                         .add("transaction_id", "string")
                                         .add("member_id", "string")
                                         .add("location_id", "string")
                                         .add("external_id", "string")
                                         .add("created_at", "timestamp")
                                         .add("updated_at", "timestamp")
                                         .add("time_at", "timestamp")
                                         .add("transaction_till_id", "string")
                                         .add("transaction_cashier_id", "string")
                                         .add("transaction_register_id", "string")
                                         .add("is_forecourt_transaction", "boolean")
                                         .add("transaction_line_item_number", "integer")
                                         .add("product_id", "string")
                                         .add("product_quantity", "double")
                                         .add("product_sale_price_per_unit", "double")
                                         .add("product_sale_price", "double")
                                         .add("product_regular_price_per_unit", "double")
                                         .add("product_regular_price", "double")
                                         .add("fuel_position_id", "string")
                                         .add("fuel_is_prepaid", "boolean")
                                         .add("payment_amount", "double")
                                         .add("payment_method", "string")
                                         .add("payment_method_card_type", "string")
                                         .add("tax_amount", "double")
                                         .add("timestamp", "timestamp"))
