from pyspark.sql.types import StructType, MapType, StringType, ArrayType

VISITS_GOLD_STAGE_1_SCHEMA = (StructType()
                              .add("product_id", "string")
                              .add("id", "string")
                              .add("day_id", "date")
                              .add("member_id", "string")
                              .add("location_id", "string")
                              .add("transaction_id", "string")
                              .add("is_forecourt_transaction", "boolean")
                              .add("created_at", "timestamp")
                              .add("timestamp", "timestamp")
                              .add("product_attributes", MapType(StringType(), StringType()))
                              .add("product_categories", ArrayType(StringType())))

VISITS_GOLD_STAGE_2_SCHEMA = (StructType()
                              .add("id", "string")
                              .add("day_id", "date")
                              .add("transaction_id", "string")
                              .add("member_id", "string")
                              .add("location_id", "string")
                              .add("is_forecourt_visit", "boolean")
                              .add("is_fuel_visit", "boolean")
                              .add("is_merch_visit", "boolean")
                              .add("is_tobacco_visit", "boolean")
                              .add("is_alcohol_visit", "boolean")
                              .add("visit_start", "timestamp")
                              .add("visit_end", "timestamp")
                              .add("visit_duration", "long")
                              .add("timestamp", "timestamp"))
