from pyspark.sql.types import StructType

ADDRESSES_SCHEMA = (StructType()
                    .add("id", "string")
                    .add("membership_id", "string")
                    .add("city", "string")
                    .add("state", "string")
                    .add("zipcode", "string")
                    .add("address1", "string")
                    .add("address2", "string")
                    .add("primary", "boolean")
                    .add("created_at", "timestamp")
                    .add("updated_at", "timestamp"))

CAMPAIGNS_SCHEMA = (StructType()
                    .add("id", "string")
                    .add("category", "string")
                    .add("chain_id", "string")
                    .add("description", "string")
                    .add("deleted_at", "timestamp")
                    .add("name", "string")
                    .add("created_at", "timestamp")
                    .add("updated_at", "timestamp")
                    .add("external_id", "string"))

CHAINS_SCHEMA = (StructType()
                 .add("id", "string")
                 .add("name", "string")
                 .add("deleted_at", "timestamp")
                 .add("created_at", "timestamp")
                 .add("updated_at", "timestamp")
                 .add("organization_id", "string")
                 .add("membership_activity_evidence", "string")
                 .add("brand_uuid", "string")
                 .add("default_points_expiration_days", "integer")
                 .add("paused_points_expiration_days", "integer"))

CONSTRAINTS_SCHEMA = (StructType()
                      .add("id", "string", False)
                      .add("offer_id", "string", False)
                      .add("constraint_type", "string", False)
                      .add("created_at", "timestamp", False)
                      .add("updated_at", "timestamp", False)
                      .add("deleted_at", "timestamp"))

FUEL_AND_CONVENIENCE_PROFILES_SCHEMA = (StructType()
                                        .add("id", "string")
                                        .add("membership_id", "string")
                                        .add("alcohol_verified", "boolean")
                                        .add("acquisition_channel", "string")
                                        .add("created_at", "timestamp")
                                        .add("updated_at", "timestamp")
                                        .add("alrtia_verified", "boolean")
                                        .add("rjr_verified", "boolean")
                                        .add("restriction_verification", "string")
                                        .add("member_data_share", "boolean"))

LOYALTY_EVENTS_SCHEMA = (StructType()
                         .add("id", "string")
                         .add("chain_id", "string")
                         .add("event_type", "string")
                         .add("event_data", "string")
                         .add("created_at", "timestamp")
                         .add("updated_at", "timestamp")
                         .add("membership_id", "string")
                         .add("backfilled_membership", "boolean")
                         .add("processed_at", "timestamp"))

MEMBERSHIPS_SCHEMA = (StructType()
                      .add("id", "string")
                      .add("chain_id", "string")
                      .add("email", "string")
                      .add("phone", "string")
                      .add("deleted_at", "timestamp")
                      .add("created_at", "timestamp")
                      .add("updated_at", "timestamp")
                      .add("state", "string")
                      .add("points", "integer")
                      .add("name", "string")
                      .add("encrypted_password", "string")
                      .add("reset_password_token", "string")
                      .add("reset_password_sent_at", "timestamp")
                      .add("custom_data", "string")
                      .add("birthdate", "date")
                      .add("first_name", "string")
                      .add("last_name", "string")
                      .add("failed_attempts", "integer")
                      .add("unlock_token", "string")
                      .add("locked_at", "timestamp")
                      .add("activity_at", "timestamp")
                      .add("customer_uuid", "string")
                      .add("program_terms_acceptance_at", "timestamp")
                      .add("home_stores", "string"))

MEMBERSHIP_POINT_TRANSACTIONS_SCHEMA = (StructType()
                                        .add("id", "string")
                                        .add("membership_id", "string")
                                        .add("quantity", "integer")
                                        .add("source_id", "string")
                                        .add("source_type", "string")
                                        .add("notes", "string")
                                        .add("created_at", "timestamp")
                                        .add("updated_at", "timestamp")
                                        .add("offer_id", "string")
                                        .add("chain_id", "string"))

MEMBERSHIPS_SEGMENTS_SCHEMA = (StructType()
                               .add("id", "string")
                               .add("membership_id", "string")
                               .add("segment_id", "string")
                               .add("deleted_at", "timestamp")
                               .add("created_at", "timestamp")
                               .add("updated_at", "timestamp")
                               .add("csv_upload", "boolean"))

META_OFFERS_SCHEMA = (StructType()
                      .add("id", "string")
                      .add("fuel_grade_id", "string")
                      .add("offer_value", "double")
                      .add("limit", "integer")
                      .add("offers_ids", "string")
                      .add("parent_id", "string")
                      .add("created_at", "timestamp")
                      .add("updated_at", "timestamp")
                      .add("loyalty_sequence_id", "string"))

OFFER_PURCHASES_SCHEMA = (StructType()
                          .add("id", "string")
                          .add("vouchered_offer_id", "string")
                          .add("purchasable_offer_id", "string")
                          .add("membership_id", "string")
                          .add("point_cost", "integer")
                          .add("returnable", "boolean")
                          .add("deleted_at", "timestamp")
                          .add("created_at", "timestamp")
                          .add("updated_at", "timestamp")
                          .add("reserved_until", "timestamp"))

OFFERS_SCHEMA = (StructType()
                 .add("id", "string")
                 .add("chain_id", "string")
                 .add("name", "string")
                 .add("description", "string")
                 .add("created_at", "timestamp")
                 .add("updated_at", "timestamp")
                 .add("external_id", "string")
                 .add("must_activate", "boolean")
                 .add("publish_at", "timestamp")
                 .add("expire_at", "timestamp")
                 .add("deleted_at", "timestamp")
                 .add("category", "string")
                 .add("custom_data", "string")
                 .add("rule_id", "string")
                 .add("cached_limit_met", "boolean")
                 .add("engagement_type", "string")
                 .add("campaign_id", "string")
                 .add("presentation_type", "string")
                 .add("age_restricted", "boolean")
                 .add("trigger_preferences",
                      StructType()
                      .add("triggerOnVisibility", "boolean")
                      .add("triggerOnFulfillment", "boolean"))
                 .add("presentation_priority", "string")
                 .add("numeric_id", "integer")
                 .add("funding_source", "string"))

PRODUCT_GROUPS_SCHEMA = (StructType()
                         .add("id", "string")
                         .add("chain_id", "string")
                         .add("name", "string")
                         .add("description", "string")
                         .add("key", "string")
                         .add("values", "string")
                         .add("created_at", "timestamp")
                         .add("updated_at", "timestamp")
                         .add("deleted_at", "timestamp"))

TRANSACTION_DATA_SCHEMA = (StructType()
                           .add("id", "string")
                           .add("transaction_id", "string")
                           .add("processing_status", "string")
                           .add("finalize_rewards_data", "string")
                           .add("created_at", "timestamp")
                           .add("updated_at", "timestamp"))

TRANSACTIONS_SCHEMA = (StructType()
                       .add("id", "string")
                       .add("location_id", "string")
                       .add("transaction_time_at", "timestamp")
                       .add("money_currency_code", "string")
                       .add("request_id", "string")
                       .add("created_at", "timestamp")
                       .add("membership_id", "string")
                       .add("partner_id", "string")
                       .add("custom_data", "string")
                       .add("processed_at", "timestamp")
                       .add("external_location_id", "string")
                       .add("external_transaction_id", "string"))


TRANSACTION_LINE_ITEMS_SCHEMA = (StructType()
                                 .add("id", "string")
                                 .add("transaction_id", "string")
                                 .add("line_item_number", "integer")
                                 .add("sku", "string")
                                 .add("promo_code", "string")
                                 .add("quantity", "double")
                                 .add("money_amount", "integer")
                                 .add("upc", "string")
                                 .add("group", "string")
                                 .add("line_item_tags", "string")
                                 .add("created_at", "timestamp")
                                 .add("product_groups", "string")
                                 .add("membership_id", "string")
                                 .add("transaction_time_at", "timestamp")
                                 .add("fuel_grade_id", "string")
                                 .add("promotion_data", "string"))
