from pyspark.sql.types import StructType

ADDRESS_SCHEMA = (StructType()
                  .add("createdAt", "timestamp")
                  .add("updatedAt", "timestamp")
                  .add("id", "integer")
                  .add("alias", "string")
                  .add("street1", "string")
                  .add("street2", "string")
                  .add("city", "string")
                  .add("state", "string")
                  .add("zipCode", "string")
                  .add("createdById", "integer")
                  .add("updatedById", "integer")
                  .add("geoLocationLatitude", "decimal(10,7)")
                  .add("geoLocationLongitude", "decimal(10,7)")
                  .add("uuid", "string")
                  .add("countryCode", "string"))

BRAND_SCHEMA = (StructType()
                .add("createdAt", "timestamp")
                .add("updatedAt", "timestamp")
                .add("uuid", "string")
                .add("id", "integer")
                .add("name", "string")
                .add("supportedPaymentTypes", "string")
                .add("supportedApplePayPaymentTypes", "string")
                .add("supportedGoogleWalletPaymentTypes", "string")
                .add("tenantId", "integer")
                .add("createdById", "integer")
                .add("updatedById", "integer"))

CUSTOMER_SCHEMA = (StructType()
                   .add("createdAt", "timestamp")
                   .add("updatedAt", "timestamp")
                   .add("id", "integer")
                   .add("uuid", "string")
                   .add("identityProviderId", "string")
                   .add("username", "string")
                   .add("email", "string")
                   .add("status", "string")
                   .add("privacyGovernance", "string")
                   .add("hasPasscode", "boolean")
                   .add("defaultLocationId", "integer")
                   .add("preferences", "string")
                   .add("createdById", "integer")
                   .add("updatedById", "integer")
                   .add("nameTitle", "string")
                   .add("nameFirst", "string")
                   .add("nameMiddle", "string")
                   .add("nameLast", "string")
                   .add("nameSuffix", "string")
                   .add("demographicsBirthday", "date")
                   .add("demographicsGender", "string")
                   .add("demographicsZipcode", "string")
                   .add("demographicsCustomdemographics", "string")
                   .add("emailVerified", "boolean")
                   .add("isNewCustomer", "boolean")
                   .add("pendingEmail", "string")
                   .add("accountType", "string")
                   .add("signUpOrigin", "string"))

LOCATION_SCHEMA = (StructType()
                   .add("createdAt", "timestamp")
                   .add("updatedAt", "timestamp")
                   .add("id", "integer")
                   .add("uuid", "string")
                   .add("brandSpecificLocationId", "string")
                   .add("addressId", "integer")
                   .add("createdById", "integer")
                   .add("updatedById", "integer")
                   .add("specialHours", "string")
                   .add("brandId", "integer")
                   .add("currencyCode", "string")
                   .add("currencySymbol", "string")
                   .add("timezone", "string")
                   .add("deletedAt", "timestamp")
                   .add("deletedById", "integer")
                   .add("attributes", "string")
                   .add("hoursOfOperation", "string")
                   .add("paymentProviderMerchantId", "string")
                   .add("altriaRcn", "string"))

SITE_STATUS_SCHEMA = (StructType()
                      .add("createdAt", "timestamp")
                      .add("updatedAt", "timestamp")
                      .add("id", "integer")
                      .add("lastMobileHeartbeatAt", "timestamp")
                      .add("lastLoyaltyHeartbeatAt", "timestamp")
                      .add("lastSiteInfoRequestMessageAt", "timestamp")
                      .add("lastSiteInfoRequestMessage", "string")
                      .add("lastMobileHeartbeatMessage", "string")
                      .add("lastLoyaltyHeartbeatMessage", "string")
                      .add("hardwareVendor", "string")
                      .add("uuid", "string")
                      .add("siteConfigurationId", "string")
                      .add("lastBackOfficeHealthCheckAt", "timestamp"))

SITE_SYSTEM_SCHEMA = (StructType()
                      .add("createdAt", "timestamp")
                      .add("updatedAt", "timestamp")
                      .add("id", "integer")
                      .add("uuid", "string")
                      .add("siteConfigurationId", "string")
                      .add("loyaltyEnabled", "boolean")
                      .add("mobileEnabled", "boolean")
                      .add("loyaltyHeartbeatsOnlyEnabled", "boolean")
                      .add("hardwareVendor", "string")
                      .add("locationId", "integer")
                      .add("createdById", "integer")
                      .add("updatedById", "integer")
                      .add("ipAddress", "string")
                      .add("username", "string")
                      .add("password", "string")
                      .add("previousPassword", "string")
                      .add("backOfficeEnabled", "boolean")
                      .add("priceBookGroup", "string")
                      .add("mashginEnabled", "boolean"))

TRANSACTION_SCHEMA = (StructType()
                      .add("createdAt", "timestamp")
                      .add("updatedAt", "timestamp")
                      .add("id", "integer")
                      .add("uuid", "string")
                      .add("customerUuid", "string")
                      .add("umti", "string")
                      .add("stac", "string")
                      .add("paymentProviderTransactionId", "string")
                      .add("startedAt", "timestamp")
                      .add("completedAt", "timestamp")
                      .add("status", "string")
                      .add("brandSpecificLocationId", "string")
                      .add("fuelingPosition", "string")
                      .add("authCode", "string")
                      .add("hardwareVendor", "string")
                      .add("transactionType", "string")
                      .add("paymentLevel", "string")
                      .add("loyaltyLevel", "string")
                      .add("fuelPumpStatus", "string")
                      .add("initiationResource", "string")
                      .add("receiptLines", "string")
                      .add("rawReceipt", "string")
                      .add("fuelReceipt", "string")
                      .add("amountDisplayprice", "string")
                      .add("amountPrice", "double")
                      .add("taxDisplayprice", "string")
                      .add("taxPrice", "double")
                      .add("refundedAmountDisplayprice", "string")
                      .add("refundedAmountPrice", "double")
                      .add("currencyCode", "string")
                      .add("currencySymbol", "string")
                      .add("additionalReceiptData", "string")
                      .add("preAuthAmountDisplayprice", "string")
                      .add("preAuthAmountPrice", "double")
                      .add("locationUuid", "string")
                      .add("primaryStatus", "string")
                      .add("secondaryStatus", "string")
                      .add("paymentInstrumentUuid", "string")
                      .add("stateChanges", "string")
                      .add("customerPreferences", "string")
                      .add("carWashDetails", "string")
                      .add("isPaymentProcessedExternally", "boolean")
                      .add("loyaltyIdentifier", "string")
                      .add("kountSessionId", "string")
                      .add("kountResponse", "string")
                      .add("posTransactionNumber", "string")
                      .add("sourceId", "integer")
                      .add("cardType", "string")
                      .add("paymentMethod", "string"))


SURVEY_SCHEMA = (StructType()
                    .add("uuid", "string")
                    .add("audienceUuid", "string")
                    .add("status", "string")
                    .add("walletId", "string")
                    .add("type", "string")
                    .add("createdAt", "timestamp")
                    .add("updatedAt", "timestamp"))

SURVEY_INSTANCE_SCHEMA = (StructType()
                    .add("uuid", "string")
                    .add("surveyUuid", "string")
                    .add("memberUuid", "string")
                    .add("dismissed", "boolean")
                    .add("dismissedAt", "timestamp")
                    .add("createdAt", "timestamp")
                    .add("updatedAt", "timestamp"))

SURVEY_QUESTION_ANSWER_SCHEMA = (StructType()
                    .add("uuid", "string")
                    .add("surveyInstanceUuid", "string")
                    .add("answer", "string")
                    .add("createdAt", "timestamp")
                    .add("updatedAt", "timestamp"))

SURVEY_QUESTION_SCHEMA = (StructType()
                    .add("uuid", "string")
                    .add("surveyUuid", "string")
                    .add("index", "integer")
                    .add("text", "string")
                    .add("createdAt", "timestamp")
                    .add("updatedAt", "timestamp"))

SURVEY_FIELD_SCHEMA = (StructType()
                    .add("uuid", "string")
                    .add("questionUuid", "string")
                    .add("label", "string")
                    .add("min", "integer")
                    .add("max", "integer")
                    .add("createdAt", "timestamp")
                    .add("updatedAt", "timestamp"))

WALLET_STEERING_SCHEMA = (StructType()
                    .add("id", "integer")
                    .add("uuid", "string")
                    .add("name", "string")
                    .add("status", "string")
                    .add("chainId", "string")
                    .add("archivedAt", "timestamp")
                    .add("createdAt", "timestamp")
                    .add("updatedAt", "timestamp"))

WALLET_STEERING_CONFIGURATION_SCHEMA = (StructType()
                    .add("id", "integer")
                    .add("uuid", "string")
                    .add("productGroupId", "string")
                    .add("reportingPeriod", "string")
                    .add("unitOfMeasure", "string")
                    .add("basis", "string")
                    .add("walletSteeringId", "integer")
                    .add("createdAt", "timestamp")
                    .add("updatedAt", "timestamp"))
