from pyspark.sql.types import ArrayType, StringType, StructType

CHAINS_SILVER_STAGE_1_SCHEMA = (StructType()
                                .add("id", "string")
                                .add("brand_id", "integer")
                                .add("brand_uuid", "string")
                                .add("brand_created_at", "timestamp")
                                .add("brand_updated_at", "timestamp")
                                .add("chain_created_at", "timestamp")
                                .add("chain_updated_at", "timestamp")
                                .add("chain_deleted_at", "timestamp")
                                .add("name", "string")
                                .add("supported_payment_types", ArrayType(StringType()))
                                .add("supported_apple_pay_payment_types", ArrayType(StringType()))
                                .add("supported_google_wallet_payment_types", ArrayType(StringType()))
                                .add("membership_activity_evidence", ArrayType(StringType()))
                                .add("default_points_expiration_days", "integer")
                                .add("paused_points_expiration_days", "integer")
                                .add("timestamp", "timestamp"))
