from pyspark.sql.types import ArrayType, StructType

from open_commerce_data_pipelines.core.schemas.models import LOCATION_HOURS_OF_OPERATION

LOCATIONS_SILVER_STAGE_1_SCHEMA = (StructType()
                                   .add("id", "string")
                                   .add("address_id", "integer")
                                   .add("brand_id", "integer")
                                   .add("chain_id", "string")
                                   .add("location_id", "integer")
                                   .add("address_created_at", "timestamp")
                                   .add("address_updated_at", "timestamp")
                                   .add("location_created_at", "timestamp")
                                   .add("location_updated_at", "timestamp")
                                   .add("location_deleted_at", "timestamp")
                                   .add("site_status_created_at", "timestamp")
                                   .add("site_status_updated_at", "timestamp")
                                   .add("site_system_created_at", "timestamp")
                                   .add("site_system_updated_at", "timestamp")
                                   .add("last_loyalty_heartbeat_at", "timestamp")
                                   .add("last_mobile_heartbeat_at", "timestamp")
                                   .add("last_site_info_request_message_at", "timestamp")
                                   .add("last_site_info_request_message", "string")
                                   .add("is_back_office_enabled", "boolean")
                                   .add("is_loyalty_enabled", "boolean")
                                   .add("is_mashgin_enabled", "boolean")
                                   .add("is_mobile_enabled", "boolean")
                                   .add("hours_of_operation", ArrayType(LOCATION_HOURS_OF_OPERATION))
                                   .add("site_configuration_id", "string")
                                   .add("name", "string")
                                   .add("timezone", "string")
                                   .add("street_1", "string")
                                   .add("street_2", "string")
                                   .add("city", "string")
                                   .add("state", "string")
                                   .add("zip_code", "string")
                                   .add("country_code", "string")
                                   .add("latitude", "decimal(10,7)")
                                   .add("longitude", "decimal(10,7)")
                                   .add("merchant_id", "string")
                                   .add("altria_rcn", "string")
                                   .add("timestamp", "timestamp"))
