from pyspark.sql.types import ArrayType, StructType, StringType

MEMBERS_AUDIENCE_HISTORY_SCHEMA = (StructType()
                                   .add("audience_id", "string")
                                   .add("joined_at", "timestamp")
                                   .add("left_at", "timestamp"))

MEMBERS_STATUS_HISTORY_SCHEMA = (StructType()
                                 .add("status", "string")
                                 .add("updated_at", "timestamp"))


MEMBERS_SILVER_STAGE_1_SCHEMA = (StructType()
                                 .add("id", "string")
                                 .add("customer_id", "string")
                                 .add("loyalty_member_id", "string")
                                 .add("email", "string")
                                 .add("is_email_verified", "boolean")
                                 .add("phone", "string")
                                 .add("username", "string")
                                 .add("first_name", "string")
                                 .add("last_name", "string")
                                 .add("birthdate", "date")
                                 .add("gender", "string")
                                 .add("state", "string")
                                 .add("zip_code", "string")
                                 .add("customer_status_current", "string")
                                 .add("customer_status_history", ArrayType(MEMBERS_STATUS_HISTORY_SCHEMA))
                                 .add("loyalty_status_current", "string")
                                 .add("loyalty_status_history", ArrayType(MEMBERS_STATUS_HISTORY_SCHEMA))
                                 .add("privacy_governance", "string")
                                 .add("default_location_id", "integer")
                                 .add("customer_type", "string")
                                 .add("customer_signup_origin", "string")
                                 .add("is_alcohol_verified", "boolean")
                                 .add("is_altria_verified", "boolean")
                                 .add("is_rjr_verified", "boolean")
                                 .add("customer_created_at", "timestamp")
                                 .add("customer_updated_at", "timestamp")
                                 .add("member_dossier_created_at", "timestamp")
                                 .add("member_dossier_updated_at", "timestamp")
                                 .add("membership_created_at", "timestamp")
                                 .add("membership_updated_at", "timestamp")
                                 .add("points_balance", "integer")
                                 .add("profile_complete_percent", "double")
                                 .add("home_stores", ArrayType(StringType()))
                                 .add("first_loyalty_transaction_at", "timestamp")
                                 .add("first_loyalty_transaction_id", "string")
                                 .add("last_loyalty_transaction_at", "timestamp")
                                 .add("last_loyalty_transaction_id", "string")
                                 .add("first_mobile_transaction_at", "timestamp")
                                 .add("first_mobile_transaction_id", "string")
                                 .add("last_mobile_transaction_at", "timestamp")
                                 .add("last_mobile_transaction_id", "string")
                                 .add("timestamp", "timestamp"))
