from pyspark.sql.types import StructType

OFFERS_SILVER_STAGE_1_SCHEMA = (StructType()
                                .add("id", "string")
                                .add("rule_id", "string")
                                .add("campaign_id", "string")
                                .add("name", "string")
                                .add("description", "string")
                                .add("created_at", "timestamp")
                                .add("updated_at", "timestamp")
                                .add("deleted_at", "timestamp")
                                .add("external_id", "string")
                                .add("is_activation_required", "boolean")
                                .add("publish_at", "timestamp")
                                .add("expire_at", "timestamp")
                                .add("category", "string")
                                .add("engagement_type", "string")
                                .add("is_cached_limit_met", "boolean")
                                .add("presentation_type", "string")
                                .add("presentation_priority", "string")
                                .add("is_further_automation_triggered_on_visibility", "boolean")
                                .add("is_further_automation_triggered_on_fulfillment", "boolean")
                                .add("is_age_restricted", "boolean")
                                .add("is_rollback", "boolean")
                                .add("funding_source", "string")
                                .add("first_fulfillment_at", "timestamp")
                                .add("first_fulfillment_id", "string")
                                .add("last_fulfillment_at", "timestamp")
                                .add("last_fulfillment_id", "string")
                                .add("constraints_updated_at", "timestamp")
                                .add("timestamp", "timestamp"))
