from pyspark.sql.types import ArrayType, StructType

TRANSACTIONS_SILVER_DISCOUNT_SCHEMA = ((StructType()
                                        .add("discount_id", "string")
                                        .add("offer_id", "string")
                                        .add("discount_amount", "double")))

TRANSACTION_LINE_ITEMS_SILVER_PROMOTION_SCHEMA = ((StructType()
                                                   .add("offer_id", "string")
                                                   .add("meta_offer_id", "string")
                                                   .add("loyalty_reward_id", "string")
                                                   .add("promotion_number", "integer")
                                                   .add("promotion_id", "string")
                                                   .add("promotion_amount", "double")
                                                   .add("promotion_amount_base", "double")
                                                   .add("promotion_reason", "string")
                                                   .add("fulfillment_count", "integer")))

TRANSACTION_LINE_ITEMS_SILVER_SCHEMA = (StructType()
                                        .add("loyalty_transaction_line_item_id", "string")
                                        .add("product_id", "string")
                                        .add("line_item_number", "integer")
                                        .add("sku", "string")
                                        .add("product_upc", "string")
                                        .add("product_merchandise_code", "string")
                                        .add("product_payment_systems_code", "string")
                                        .add("product_quantity", "double")
                                        .add("product_sale_price_per_unit", "double")
                                        .add("product_sale_price", "double")
                                        .add("product_regular_price_per_unit", "double")
                                        .add("product_regular_price", "double")
                                        .add("fuel_grade", "string")
                                        .add("fuel_position_id", "string")
                                        .add("fuel_is_prepaid", "boolean")
                                        .add("promotions", ArrayType(TRANSACTION_LINE_ITEMS_SILVER_PROMOTION_SCHEMA))
                                        .add("mobile_transaction_line_item_created_at", "timestamp")
                                        .add("mobile_transaction_line_item_updated_at", "timestamp")
                                        .add("transaction_data_created_at", "timestamp")
                                        .add("transaction_data_updated_at", "timestamp")
                                        .add("transaction_line_item_created_at", "timestamp"))

TRANSACTIONS_SILVER_STAGE_1_SCHEMA = (StructType()
                                      .add("id", "string")
                                      .add("day_id", "date")
                                      .add("member_id", "string")
                                      .add("loyalty_member_id", "string")
                                      .add("loyalty_transaction_id", "string")
                                      .add("customer_id", "string")
                                      .add("mobile_transaction_id", "string")
                                      .add("location_id", "string")
                                      .add("external_id", "string")
                                      .add("umti", "string")
                                      .add("transaction_type", "string")
                                      .add("transaction_pos_timestamp", "timestamp")
                                      .add("transaction_pos_timestamp_local", "timestamp")
                                      .add("transaction_till_id", "string")
                                      .add("transaction_cashier_id", "string")
                                      .add("transaction_register_id", "string")
                                      .add("is_forecourt_transaction", "boolean")
                                      .add("payment_amount", "double")
                                      .add("payment_method", "string")
                                      .add("payment_method_card_type", "string")
                                      .add("tax_amount", "double")
                                      .add("points_quantity", "integer")
                                      .add("mobile_transaction_primary_status", "string")
                                      .add("mobile_transaction_secondary_status", "string")
                                      .add("mobile_transaction_state_changes",
                                           ArrayType(StructType()
                                                     .add("updated_at", "timestamp")
                                                     .add("primary_status", "string")
                                                     .add("secondary_status", "string")))
                                      .add("mobile_transaction_completed_at", "timestamp")
                                      .add("mobile_transaction_created_at", "timestamp")
                                      .add("mobile_transaction_started_at", "timestamp")
                                      .add("mobile_transaction_updated_at", "timestamp")
                                      .add("loyalty_transaction_created_at", "timestamp")
                                      .add("loyalty_transaction_processed_at", "timestamp")
                                      .add("loyalty_transaction_time_at", "timestamp")
                                      .add("points_transaction_created_at", "timestamp")
                                      .add("points_transaction_updated_at", "timestamp")
                                      .add("transaction_data_created_at", "timestamp")
                                      .add("transaction_data_updated_at", "timestamp")
                                      .add("transaction_line_item_created_at", "timestamp")
                                      .add("transaction_line_item_updated_at", "timestamp")
                                      .add("line_items", ArrayType(TRANSACTION_LINE_ITEMS_SILVER_SCHEMA))
                                      .add("transaction_discounts", ArrayType(TRANSACTIONS_SILVER_DISCOUNT_SCHEMA))
                                      .add("timestamp", "timestamp"))
