from pyspark.sql.types import ArrayType, StructType

FINALIZE_REWARDS_REQUEST_SCHEMA = StructType().fromJson({
    "fields": [{
        "metadata": {},
        "name": "LoyaltyID",
        "nullable": True,
        "type": {
            "fields": [{
                "metadata": {},
                "name": "_entryMethod",
                "nullable": True,
                "type": "string"
            }, {
                "metadata": {},
                "name": "_inner",
                "nullable": True,
                "type": "string"
            }],
            "type": "struct"
        }
    }, {
        "metadata": {},
        "name": "RequestHeader",
        "nullable": True,
        "type": {
            "fields": [{
                "metadata": {},
                "name": "InstrumentDefinitionVersion",
                "nullable": True,
                "type": "long"
            }, {
                "metadata": {},
                "name": "LoyaltyOfflineFlag",
                "nullable": True,
                "type": {
                    "fields": [{
                        "metadata": {},
                        "name": "_inner",
                        "nullable": True,
                        "type": "string"
                    }, {
                        "metadata": {},
                        "name": "_value",
                        "nullable": True,
                        "type": "string"
                    }],
                    "type": "struct"
                }
            }, {
                "metadata": {},
                "name": "LoyaltySequenceID",
                "nullable": True,
                "type": "string"
            }, {
                "metadata": {},
                "name": "POSLoyaltyInterfaceVersion",
                "nullable": True,
                "type": "double"
            }, {
                "metadata": {},
                "name": "POSSequenceID",
                "nullable": True,
                "type": "string"
            }, {
                "metadata": {},
                "name": "StoreLocationID",
                "nullable": True,
                "type": "string"
            }, {
                "metadata": {},
                "name": "VendorModelVersion",
                "nullable": True,
                "type": "string"
            }, {
                "metadata": {},
                "name": "VendorName",
                "nullable": True,
                "type": "string"
            }],
            "type": "struct"
        }
    }, {
        "metadata": {},
        "name": "TransactionData",
        "nullable": True,
        "type": {
            "fields": [{
                "metadata": {},
                "name": "TransactionDetailGroup",
                "nullable": True,
                "type": {
                    "fields": [{
                        "metadata": {},
                        "name": "TransactionLine",
                        "nullable": True,
                        "type": {
                            "containsNull": True,
                            "elementType": {
                                "fields": [{
                                    "metadata": {},
                                    "name": "FuelLine",
                                    "nullable": True,
                                    "type": {
                                        "fields": [{
                                            "metadata": {},
                                            "name": "ActualSalesPrice",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "Description",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "FuelGradeID",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "FuelPositionID",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "PaymentSystemsProductCode",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "Promotion",
                                            "nullable": True,
                                            "type": {
                                                "containsNull": True,
                                                "elementType": {
                                                    "fields": [{
                                                        "metadata": {},
                                                        "name": "LoyaltyRewardID",
                                                        "nullable": True,
                                                        "type": "string"
                                                    }, {
                                                        "metadata": {},
                                                        "name": "PromotionAmount",
                                                        "nullable": True,
                                                        "type": "double"
                                                    }, {
                                                        "metadata": {},
                                                        "name": "PromotionID",
                                                        "nullable": True,
                                                        "type": "string"
                                                    }, {
                                                        "metadata": {},
                                                        "name": "PromotionReason",
                                                        "nullable": True,
                                                        "type": "string"
                                                    }],
                                                    "type": "struct"
                                                },
                                                "type": "array"
                                            }
                                        }, {
                                            "metadata": {},
                                            "name": "RegularSellPrice",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesAmount",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesQuantity",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesUOM",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "ServiceLevelCode",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "_fuelPrepayFlag",
                                            "nullable": True,
                                            "type": "string"
                                        }],
                                        "type": "struct"
                                    }
                                }, {
                                    "metadata": {},
                                    "name": "ItemLine",
                                    "nullable": True,
                                    "type": {
                                        "fields": [{
                                            "metadata": {},
                                            "name": "ActualSalesPrice",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "Description",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "ItemCode",
                                            "nullable": True,
                                            "type": {
                                                "fields": [{
                                                    "metadata": {},
                                                    "name": "POSCode",
                                                    "nullable": True,
                                                    "type": "string"
                                                }, {
                                                    "metadata": {},
                                                    "name": "POSCodeFormat",
                                                    "nullable": True,
                                                    "type": {
                                                        "fields": [{
                                                            "metadata": {},
                                                            "name": "_format",
                                                            "nullable": True,
                                                            "type": "string"
                                                        }, {
                                                            "metadata": {},
                                                            "name": "_inner",
                                                            "nullable": True,
                                                            "type": "string"
                                                        }],
                                                        "type": "struct"
                                                    }
                                                }, {
                                                    "metadata": {},
                                                    "name": "POSCodeModifier",
                                                    "nullable": True,
                                                    "type": "long"
                                                }],
                                                "type": "struct"
                                            }
                                        }, {
                                            "metadata": {},
                                            "name": "MerchandiseCode",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "PaymentSystemsProductCode",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "Promotion",
                                            "nullable": True,
                                            "type": {
                                                "containsNull": True,
                                                "elementType": {
                                                    "fields": [{
                                                        "metadata": {},
                                                        "name": "LoyaltyRewardID",
                                                        "nullable": True,
                                                        "type": "string"
                                                    }, {
                                                        "metadata": {},
                                                        "name": "PromotionAmount",
                                                        "nullable": True,
                                                        "type": "double"
                                                    }, {
                                                        "metadata": {},
                                                        "name": "PromotionID",
                                                        "nullable": True,
                                                        "type": "string"
                                                    }, {
                                                        "metadata": {},
                                                        "name": "PromotionReason",
                                                        "nullable": True,
                                                        "type": "string"
                                                    }],
                                                    "type": "struct"
                                                },
                                                "type": "array"
                                            }
                                        }, {
                                            "metadata": {},
                                            "name": "RegularSellPrice",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesAmount",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesQuantity",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesUOM",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "SellingUnits",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "_discountable",
                                            "nullable": True,
                                            "type": "string"
                                        }],
                                        "type": "struct"
                                    }
                                }, {
                                    "metadata": {},
                                    "name": "LineNumber",
                                    "nullable": True,
                                    "type": "long"
                                }, {
                                    "metadata": {},
                                    "name": "MerchandiseCodeLine",
                                    "nullable": True,
                                    "type": {
                                        "fields": [{
                                            "metadata": {},
                                            "name": "ActualSalesPrice",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "Description",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "MerchandiseCode",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "PaymentSystemsProductCode",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesAmount",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesQuantity",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "SalesUOM",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "_discountable",
                                            "nullable": True,
                                            "type": "string"
                                        }],
                                        "type": "struct"
                                    }
                                }, {
                                    "metadata": {},
                                    "name": "TenderInfo",
                                    "nullable": True,
                                    "type": {
                                        "fields": [{
                                            "metadata": {},
                                            "name": "ChangeFlag",
                                            "nullable": True,
                                            "type": {
                                                "fields": [{
                                                    "metadata": {},
                                                    "name": "_inner",
                                                    "nullable": True,
                                                    "type": "string"
                                                }, {
                                                    "metadata": {},
                                                    "name": "_value",
                                                    "nullable": True,
                                                    "type": "string"
                                                }],
                                                "type": "struct"
                                            }
                                        }, {
                                            "metadata": {},
                                            "name": "ISOPrefix",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "LoyaltyRewardID",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "TenderAmount",
                                            "nullable": True,
                                            "type": {
                                                "fields": [{
                                                    "metadata": {},
                                                    "name": "_currency",
                                                    "nullable": True,
                                                    "type": "string"
                                                }, {
                                                    "metadata": {},
                                                    "name": "_inner",
                                                    "nullable": True,
                                                    "type": "double"
                                                }],
                                                "type": "struct"
                                            }
                                        }, {
                                            "metadata": {},
                                            "name": "TenderCode",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "TenderSubCode",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "_entryMethod",
                                            "nullable": True,
                                            "type": "string"
                                        }],
                                        "type": "struct"
                                    }
                                }, {
                                    "metadata": {},
                                    "name": "TransactionTax",
                                    "nullable": True,
                                    "type": {
                                        "fields": [{
                                            "metadata": {},
                                            "name": "TaxableSalesAmount",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "TaxableSalesRefundedAmount",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "TaxCollectedAmount",
                                            "nullable": True,
                                            "type": "double"
                                        }, {
                                            "metadata": {},
                                            "name": "TaxLevelID",
                                            "nullable": True,
                                            "type": "string"
                                        }, {
                                            "metadata": {},
                                            "name": "TaxRefundedAmount",
                                            "nullable": True,
                                            "type": "double"
                                        }],
                                        "type": "struct"
                                    }
                                }, {
                                    "metadata": {},
                                    "name": "_status",
                                    "nullable": True,
                                    "type": "string"
                                }],
                                "type": "struct"
                            },
                            "type": "array"
                        }
                    }],
                    "type": "struct"
                }
            }, {
                "metadata": {},
                "name": "TransactionHeader",
                "nullable": True,
                "type": {
                    "fields": [{
                        "metadata": {},
                        "name": "BusinessPeriod",
                        "nullable": True,
                        "type": {
                            "fields": [{
                                "metadata": {},
                                "name": "BeginDate",
                                "nullable": True,
                                "type": "date"
                            }, {
                                "metadata": {},
                                "name": "BeginTime",
                                "nullable": True,
                                "type": "string"
                            }, {
                                "metadata": {},
                                "name": "BusinessDate",
                                "nullable": True,
                                "type": "date"
                            }, {
                                "metadata": {},
                                "name": "EndDate",
                                "nullable": True,
                                "type": "date"
                            }, {
                                "metadata": {},
                                "name": "EndTime",
                                "nullable": True,
                                "type": "string"
                            }, {
                                "metadata": {},
                                "name": "PrimaryReportPeriod",
                                "nullable": True,
                                "type": {
                                    "fields": [{
                                        "metadata": {},
                                        "name": "_inner",
                                        "nullable": True,
                                        "type": "long"
                                    }, {
                                        "metadata": {},
                                        "name": "_interval",
                                        "nullable": True,
                                        "type": "string"
                                    }],
                                    "type": "struct"
                                }
                            }],
                            "type": "struct"
                        }
                    }, {
                        "metadata": {},
                        "name": "CashierID",
                        "nullable": True,
                        "type": "string"
                    }, {
                        "metadata": {},
                        "name": "EventStartDate",
                        "nullable": True,
                        "type": "date"
                    }, {
                        "metadata": {},
                        "name": "EventStartTime",
                        "nullable": True,
                        "type": "string"
                    }, {
                        "metadata": {},
                        "name": "FuelPositionID",
                        "nullable": True,
                        "type": "string"
                    }, {
                        "metadata": {},
                        "name": "OutsideSalesFlag",
                        "nullable": True,
                        "type": {
                            "fields": [{
                                "metadata": {},
                                "name": "_inner",
                                "nullable": True,
                                "type": "string"
                            }, {
                                "metadata": {},
                                "name": "_value",
                                "nullable": True,
                                "type": "string"
                            }],
                            "type": "struct"
                        }
                    }, {
                        "metadata": {},
                        "name": "POSTransactionID",
                        "nullable": True,
                        "type": "string"
                    }, {
                        "metadata": {},
                        "name": "RegisterID",
                        "nullable": True,
                        "type": "string"
                    }, {
                        "metadata": {},
                        "name": "TillID",
                        "nullable": True,
                        "type": "string"
                    }],
                    "type": "struct"
                }
            }],
            "type": "struct"
        }
    }, {
        "metadata": {},
        "name": "_ns2",
        "nullable": True,
        "type": "string"
    }, {
        "metadata": {},
        "name": "_ns3",
        "nullable": True,
        "type": "string"
    }, {
        "metadata": {},
        "name": "_ns4",
        "nullable": True,
        "type": "string"
    }],
    "type": "struct"
})

FINALIZE_REWARDS_REQUEST_TRANSACTION_LINE_SCHEMA = ArrayType.fromJson({
    "containsNull": True,
    "elementType": {
        "fields": [{
            "metadata": {},
            "name": "FuelLine",
            "nullable": True,
            "type": {
                "fields": [{
                    "metadata": {},
                    "name": "ActualSalesPrice",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "Description",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "FuelGradeID",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "FuelPositionID",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "PaymentSystemsProductCode",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "Promotion",
                    "nullable": True,
                    "type": {
                        "containsNull": True,
                        "elementType": {
                            "fields": [{
                                "metadata": {},
                                "name": "LoyaltyRewardID",
                                "nullable": True,
                                "type": "string"
                            }, {
                                "metadata": {},
                                "name": "PromotionAmount",
                                "nullable": True,
                                "type": "double"
                            }, {
                                "metadata": {},
                                "name": "PromotionID",
                                "nullable": True,
                                "type": "string"
                            }, {
                                "metadata": {},
                                "name": "PromotionReason",
                                "nullable": True,
                                "type": "string"
                            }],
                            "type": "struct"
                        },
                        "type": "array"
                    }
                }, {
                    "metadata": {},
                    "name": "RegularSellPrice",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "SalesAmount",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "SalesQuantity",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "SalesUOM",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "ServiceLevelCode",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "_fuelPrepayFlag",
                    "nullable": True,
                    "type": "string"
                }],
                "type": "struct"
            }
        }, {
            "metadata": {},
            "name": "ItemLine",
            "nullable": True,
            "type": {
                "fields": [{
                    "metadata": {},
                    "name": "ActualSalesPrice",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "Description",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "ItemCode",
                    "nullable": True,
                    "type": {
                        "fields": [{
                            "metadata": {},
                            "name": "POSCode",
                            "nullable": True,
                            "type": "string"
                        }, {
                            "metadata": {},
                            "name": "POSCodeFormat",
                            "nullable": True,
                            "type": {
                                "fields": [{
                                    "metadata": {},
                                    "name": "_format",
                                    "nullable": True,
                                    "type": "string"
                                }, {
                                    "metadata": {},
                                    "name": "_inner",
                                    "nullable": True,
                                    "type": "string"
                                }],
                                "type": "struct"
                            }
                        }, {
                            "metadata": {},
                            "name": "POSCodeModifier",
                            "nullable": True,
                            "type": "long"
                        }],
                        "type": "struct"
                    }
                }, {
                    "metadata": {},
                    "name": "MerchandiseCode",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "PaymentSystemsProductCode",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "Promotion",
                    "nullable": True,
                    "type": {
                        "containsNull": True,
                        "elementType": {
                            "fields": [{
                                "metadata": {},
                                "name": "LoyaltyRewardID",
                                "nullable": True,
                                "type": "string"
                            }, {
                                "metadata": {},
                                "name": "PromotionAmount",
                                "nullable": True,
                                "type": "double"
                            }, {
                                "metadata": {},
                                "name": "PromotionID",
                                "nullable": True,
                                "type": "string"
                            }, {
                                "metadata": {},
                                "name": "PromotionReason",
                                "nullable": True,
                                "type": "string"
                            }],
                            "type": "struct"
                        },
                        "type": "array"
                    }
                }, {
                    "metadata": {},
                    "name": "RegularSellPrice",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "SalesAmount",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "SalesQuantity",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "SalesUOM",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "SellingUnits",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "_discountable",
                    "nullable": True,
                    "type": "string"
                }],
                "type": "struct"
            }
        }, {
            "metadata": {},
            "name": "LineNumber",
            "nullable": True,
            "type": "long"
        }, {
            "metadata": {},
            "name": "MerchandiseCodeLine",
            "nullable": True,
            "type": {
                "fields": [{
                    "metadata": {},
                    "name": "ActualSalesPrice",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "Description",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "MerchandiseCode",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "PaymentSystemsProductCode",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "SalesAmount",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "SalesQuantity",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "SalesUOM",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "_discountable",
                    "nullable": True,
                    "type": "string"
                }],
                "type": "struct"
            }
        }, {
            "metadata": {},
            "name": "TenderInfo",
            "nullable": True,
            "type": {
                "fields": [{
                    "metadata": {},
                    "name": "ChangeFlag",
                    "nullable": True,
                    "type": {
                        "fields": [{
                            "metadata": {},
                            "name": "_inner",
                            "nullable": True,
                            "type": "string"
                        }, {
                            "metadata": {},
                            "name": "_value",
                            "nullable": True,
                            "type": "string"
                        }],
                        "type": "struct"
                    }
                }, {
                    "metadata": {},
                    "name": "ISOPrefix",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "LoyaltyRewardID",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "TenderAmount",
                    "nullable": True,
                    "type": {
                        "fields": [{
                            "metadata": {},
                            "name": "_currency",
                            "nullable": True,
                            "type": "string"
                        }, {
                            "metadata": {},
                            "name": "_inner",
                            "nullable": True,
                            "type": "double"
                        }],
                        "type": "struct"
                    }
                }, {
                    "metadata": {},
                    "name": "TenderCode",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "TenderSubCode",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "_entryMethod",
                    "nullable": True,
                    "type": "string"
                }],
                "type": "struct"
            }
        }, {
            "metadata": {},
            "name": "TransactionTax",
            "nullable": True,
            "type": {
                "fields": [{
                    "metadata": {},
                    "name": "TaxableSalesAmount",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "TaxableSalesRefundedAmount",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "TaxCollectedAmount",
                    "nullable": True,
                    "type": "double"
                }, {
                    "metadata": {},
                    "name": "TaxLevelID",
                    "nullable": True,
                    "type": "string"
                }, {
                    "metadata": {},
                    "name": "TaxRefundedAmount",
                    "nullable": True,
                    "type": "double"
                }],
                "type": "struct"
            }
        }, {
            "metadata": {},
            "name": "_status",
            "nullable": True,
            "type": "string"
        }],
        "type": "struct"
    }
})
